### ISSUE TITLE
Error When we deploy

### ISSUE THREAD

**Issue by mahavirvataliya** [waldocollective/buildpack-mkdocs#1]
remote: -----> Installing nginx (nginx-1.7.2)
remote:  !     Push rejected, failed to compile MkDocs app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to cloint-docs.

**Comment by adamcharnock** [comment]
Hello @mahavirvataliya, I'm sorry to say this project isn't maintained any more. I should probably remove it.

**Comment by mahavirvataliya** [comment]
Thanks for your reply. I have created my own docker file like 

```
FROM python:2.7
COPY ./app-docs /app-docs/
WORKDIR /app-docs/


RUN pip install mkdocs
RUN pip install mkdocs-material

# Expose MkDocs development server port
# ENTRYPOINT ["mkdocs"]
# Start development server by default
CMD mkdocs serve -a 0.0.0.0:$PORT 

```

deployed using container
